version: '3.9'

services:
  mongo_db:
    container_name: mongo_db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 9000:9000
    environment:
      PORT: 9000
      MONGO_DB_URI: mongodb://mongo_db:27017
      DB_NAME: notes
      NAME: dev
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
